Repository mikey0000/Mammotion-HA, pull requests merged in 2024-09, with the labels that each got.

#98 Update Wi-Fi Support Status in Documentation
  info.md
Labels: enhancement, Review effort [1-5]: 1

#101 Enhance Czech Translations in cs.json
  custom_components/mammotion/translations/cs.json
Labels: enhancement, Review effort [1-5]: 2

#102 Update German translations with new terms and corrections
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#109 Enhance Czech Translations in cs.json for Mammotion
  custom_components/mammotion/translations/cs.json
Labels: enhancement, Review effort [1-5]: 2

#113 Update de.json for new terms and options
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#111 Enhance Config Flow and Add Translations for Error Handling
  .pre-commit-config.yaml
  custom_components/mammotion/__init__.py
  custom_components/mammotion/button.py
  custom_components/mammotion/config_flow.py
  custom_components/mammotion/const.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/device_tracker.py
  custom_components/mammotion/entity.py
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/number.py
  custom_components/mammotion/select.py
  custom_components/mammotion/sensor.py
  custom_components/mammotion/switch.py
  custom_components/mammotion/translations/cs.json
  custom_components/mammotion/translations/de.json
  custom_components/mammotion/translations/en.json
  custom_components/mammotion/translations/fr.json
  custom_components/mammotion/translations/nl.json
  custom_components/mammotion/translations/pl.json
  custom_components/mammotion/translations/ro.json
  hacs.json
  mypy.ini
  poetry.lock
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 3

#121 Enhance Czech Translation Formatting and Completeness
  custom_components/mammotion/translations/cs.json
Labels: enhancement, Review effort [1-5]: 2

#124 Update de.json with new and modified translation terms
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#126 Enhance MQTT handling, update translations, and fix bugs
  custom_components/mammotion/__init__.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/select.py
  custom_components/mammotion/translations/de.json
  custom_components/mammotion/translations/pl.json
  poetry.lock
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#132 Enhance Device Management and Translations in Mammotion Component
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/translations/cs.json
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 4

#133 Update de.json with new term for clearing all map data
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#134 Enhance Mammotion integration with data management and translation updates
  custom_components/mammotion/__init__.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/switch.py
  custom_components/mammotion/translations/de.json
  poetry.lock
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#136 Add Mowing Service with Customizable Options
  custom_components/mammotion/__init__.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/services.yaml
  custom_components/mammotion/strings.json
  custom_components/mammotion/switch.py
  custom_components/mammotion/translations/en.json
Labels: enhancement, Review effort [1-5]: 4

#147 Cast Area Hashes to Integer for Consistency
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/switch.py
Labels: enhancement, Review effort [1-5]: 2

#140 Add Job Cancellation Service for Lawn Mower
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/services.yaml
  custom_components/mammotion/strings.json
  custom_components/mammotion/translations/en.json
Labels: enhancement, Review effort [1-5]: 3

#135 Enhance LawnMower State Management and Error Handling
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/strings.json
  custom_components/mammotion/translations/en.json
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#141 Enhance Device Management and Update Translations for Mowing Service
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#158 Improve French Translations for Mammotion Component
  custom_components/mammotion/translations/fr.json
Labels: enhancement, Review effort [1-5]: 2

#160 Enhance translation strings for improved clarity and consistency
  custom_components/mammotion/translations/en.json
Labels: enhancement, Review effort [1-5]: 2

#156 touchup lawn_mower.py merge
  custom_components/mammotion/lawn_mower.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#112 Enhance Lawn Mower Activity State Handling and Update Compatibility
  custom_components/mammotion/lawn_mower.py
  hacs.json
Labels: enhancement, Review effort [1-5]: 2, other

#161 Enhance Cloud Management and Update Translations for Mammotion
  custom_components/mammotion/__init__.py
  custom_components/mammotion/const.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/entity.py
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/number.py
  custom_components/mammotion/translations/de.json
  custom_components/mammotion/translations/en.json
  hacs.json
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 4, bug_fix
