Repository mikey0000/Mammotion-HA, pull requests merged in 2024-08, with the labels that each got.

#57 Refactor Measurement Units to Use Constants in Mammotion Sensor
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/sensor.py
Labels: enhancement, Review effort [1-5]: 2

#74 Add Romanian Language Support for Mammotion
  custom_components/mammotion/translations/ro.json
Labels: enhancement, Review effort [1-5]: 2

#73 Add Czech Language Support for Mammotion Mower
  custom_components/mammotion/translations/cs.json
Labels: enhancement, Review effort [1-5]: 2

#76 Add Multi-Language Support for Mammotion
  custom_components/mammotion/translations/cs.json
  custom_components/mammotion/translations/en.json
  custom_components/mammotion/translations/fr.json
  custom_components/mammotion/translations/it.json
  custom_components/mammotion/translations/nl.json
  custom_components/mammotion/translations/ro.json
Labels: enhancement, Review effort [1-5]: 4

#78 Add German Language Support for Mammotion-HA
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#75 Enhance Mammotion Integration with Wi-Fi Configuration
  FUNDING.yml
  README.md
  custom_components/mammotion/__init__.py
  custom_components/mammotion/button.py
  custom_components/mammotion/config_flow.py
  custom_components/mammotion/const.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/device_tracker.py
  custom_components/mammotion/entity.py
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/number.py
  custom_components/mammotion/select.py
  custom_components/mammotion/sensor.py
  custom_components/mammotion/strings.json
  custom_components/mammotion/switch.py
  custom_components/mammotion/translations/cs.json
  custom_components/mammotion/translations/de.json
  custom_components/mammotion/translations/en.json
  custom_components/mammotion/translations/fr.json
  custom_components/mammotion/translations/it.json
  custom_components/mammotion/translations/nl.json
  custom_components/mammotion/translations/ro.json
  poetry.lock
  pyproject.toml
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#82 Enhanced French Translations and Configuration Options
  custom_components/mammotion/translations/fr.json
Labels: enhancement, Review effort [1-5]: 2

#86 Enhance German translations for Mammotion configuration variables
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#93 Fix JSON Formatting Issues in nl.json
  custom_components/mammotion/translations/nl.json
Labels: enhancement, Review effort [1-5]: 1
