Repository mikey0000/Mammotion-HA, pull requests merged in 2024-10, with the labels that each got.

#162 Enhance de.json with new terms for cancel_job service
  custom_components/mammotion/translations/de.json
Labels: enhancement, Review effort [1-5]: 2

#166 Enhance cloud error handling and fix session reload issues
  custom_components/mammotion/const.py
  custom_components/mammotion/coordinator.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#167 Upgrade pymammotion to version 0.2.59
  custom_components/mammotion/manifest.json
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 1

#172 Standardization of Terminology in Translations
  custom_components/mammotion/translations/en.json
Labels: enhancement, Review effort [1-5]: 2

#194 add automatic translations and add connection and maintenance data
  .github/workflows/crowdin.yml
  README.md
  crowdin.yml
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/sensor.py
  custom_components/mammotion/strings.json
  custom_components/mammotion/translations/cs.json
  custom_components/mammotion/translations/de.json
  custom_components/mammotion/translations/en.json
  custom_components/mammotion/translations/fr.json
  custom_components/mammotion/translations/it.json
  custom_components/mammotion/translations/nl.json
  custom_components/mammotion/translations/pl.json
  custom_components/mammotion/translations/ro.json
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 4
