Repository mikey0000/Mammotion-HA, pull requests merged in 2025-03, with the labels that each got.

#227 Dev
  .github/workflows/release.yml
  custom_components/mammotion/__init__.py
  custom_components/mammotion/binary_sensor.py
  custom_components/mammotion/button.py
  custom_components/mammotion/camera.py
  custom_components/mammotion/config_flow.py
  custom_components/mammotion/const.py
  custom_components/mammotion/coordinator.py
  custom_components/mammotion/device_tracker.py
  custom_components/mammotion/entity.py
  custom_components/mammotion/lawn_mower.py
  custom_components/mammotion/manifest.json
  custom_components/mammotion/models.py
  custom_components/mammotion/number.py
  custom_components/mammotion/select.py
  custom_components/mammotion/sensor.py
  custom_components/mammotion/switch.py
  mypy.ini
  poetry.lock
  pyproject.toml
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#240 Add translations for select options in services
  custom_components/mammotion/services.yaml
  custom_components/mammotion/strings.json
  custom_components/mammotion/translations/en.json
Labels: enhancement, Review effort [1-5]: 4

#253 Update README.md with HA min version
  README.md
Labels: documentation, Review effort [1-5]: 1

#259 Improve entity icons and translations
  custom_components/mammotion/icons.json
  custom_components/mammotion/translations/en.json
Labels: enhancement, Review effort [1-5]: 3
